receivers:
  otlp:
    protocols:
      grpc:

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 800

  batch:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: default
  awsxray:
    region: us-east-1


extensions:
  health_check:
  pprof:
  zpages:
  memory_ballast:
    size_mib: 512

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [prometheus]
