receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 5s
          static_configs:
            - targets: [0.0.0.0:8888]

processors:
  memory_limiter:
    check_interval: 5s
    limit_mib: 4000
    spike_limit_mib: 500

  batch:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: default

extensions:
  health_check:
  pprof:
  zpages:
  memory_ballast:
    size_mib: 512

service:
  pipelines:
    metrics:
      receivers: [prometheus]
     # processors: [batch, memory_limiter]
      exporters: [prometheus]
