receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: 0.0.0.0:12346

exporters:
  prometheus:
    endpoint: '0.0.0.0:9464'

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [spanmetrics, batch]
    metrics:
      receivers: [otlp/spanmetrics]
      exporters: [prometheus]
      processors: [batch]
