receivers:
  otlp:
    protocols:
      grpc:

processors:
  memory_limiter:
    check_interval: 5s
    limit_mib: 4000
    spike_limit_mib: 500

  batch:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: default

extensions:
  health_check:
  pprof:
  zpages:
  memory_ballast:
    size_mib: 512

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
